### ISSUE TITLE
Field name for relevant website?

### ISSUE THREAD

**Issue by Falken42** [LukeBalizet/TwoMinutePapersData#4]
I was looking for information to add to the "[Real-Time Shading With Area Light Sources](https://www.youtube.com/watch?v=SC0D7aJOySY)" (YouTube link) paper, and the video description contains a link to the paper's website.

Since [the website](https://eheitzresearch.wordpress.com/415-2/) has a nice overview and description of the paper with helpful animations, I think it would be good if the `data.json` also contained a link to a paper's website (if one exists) in addition to a direct download link to the paper.

Since `url` is used to point to the YouTube video, what would be a good field name choice for a website?  Here's a few ideas to get the discussion rolling:

1. `www`
2. `website`
3. `weburl`

Thoughts?

**Comment by LukeBalizet** [comment]
Since a video may have multiple associated papers, what if an associated paper was its own object? This allows papers to have multiple fields, including a website field.
